version: '3.8'

services:
  banza_db:
    build:
      dockerfile: Dockerfile.database
    env_file:
      - .env
    ports:
      - 5432:5432
  
  banza_api:
    build: .
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - 8000:8000
   